// <auto-generated />
namespace CITOFacturacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatedOneToManyRelationshipBetweenSubDivision2ndLvAndNeighborhood : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatedOneToManyRelationshipBetweenSubDivision2ndLvAndNeighborhood));
        
        string IMigrationMetadata.Id
        {
            get { return "201907311904289_CreatedOneToManyRelationshipBetweenSubDivision2ndLvAndNeighborhood"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
