// <auto-generated />
namespace CITOFacturacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatedOneToManyRelationshipBetweenSubDivisionAndSubDivision2ndLv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatedOneToManyRelationshipBetweenSubDivisionAndSubDivision2ndLv));
        
        string IMigrationMetadata.Id
        {
            get { return "201907311900086_CreatedOneToManyRelationshipBetweenSubDivisionAndSubDivision2ndLv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
